// <auto-generated />
using System;
using EAuction.Participant.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EAuction.Participant.Persistence.Migrations
{
    [DbContext(typeof(ParticipantDbContext))]
    [Migration("20261007072401_AddAuctionCancellation")]
    partial class AddAuctionCancellation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EAuction.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aggregateid");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aggregatetype");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("RelayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("relayed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("RelayedAt", "CreatedAt");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("EAuction.Participant.Domain.AuctionTerms", b =>
                {
                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid");

                    b.Property<int>("BidderVisibility")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BookletDocumentId")
                        .HasColumnType("uuid");

                    b.Property<long>("BookletPriceMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DepositMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AuctionId");

                    b.ToTable("auction_terms", (string)null);
                });

            modelBuilder.Entity("EAuction.Participant.Domain.Bidder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("NafathVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("ProfileCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.ToTable("bidder", (string)null);
                });

            modelBuilder.Entity("EAuction.Participant.Domain.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcceptedBookletDocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BidderId")
                        .HasColumnType("uuid");

                    b.Property<string>("BookletPaymentRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("BookletPurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("BookletRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DepositAppliedToPurchase")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("DepositClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepositClosedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DepositClosureReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("DepositForfeited")
                        .HasColumnType("boolean");

                    b.Property<int?>("DepositMethod")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DepositPaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepositPaymentRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DepositRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DepositResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EligibleAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuaranteeDocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("GuaranteeExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("GuaranteeRejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuaranteeRejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("GuaranteeVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuaranteeVerifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("KeyEpoch")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PaymentFailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentFailurePurpose")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PaymentFailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("TermsAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("AuctionId", "BidderId")
                        .IsUnique();

                    b.ToTable("subscription", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
