#!/usr/bin/env bash
#
# Brings the demo up on the VM. Run it on the VM, from the repository root.
#
#   deploy/vm/deploy.sh [--no-seed] [--rebuild]
#
# Safe to re-run: .env is generated once and kept, images rebuild only when
# their inputs changed, and the one-shot provisioning jobs are idempotent.
set -euo pipefail

cd "$(dirname "$0")/../.."          # repository root
VM_DIR="deploy/vm"
BASE="deploy/compose/docker-compose.yml"
OVERRIDE="$VM_DIR/docker-compose.vm.yml"
ENV_FILE="$VM_DIR/.env"
HOST="auctions.westus2.cloudapp.azure.com"

SEED=1
REBUILD=""
for a in "$@"; do
  case "$a" in
    --no-seed) SEED=0 ;;
    --rebuild) REBUILD="--no-cache" ;;
    *) echo "unknown option: $a" >&2; exit 2 ;;
  esac
done

say() { printf '\n\033[1m%s\033[0m\n' "$*"; }
die() { printf '\033[31m%s\033[0m\n' "$*" >&2; exit 1; }

command -v docker >/dev/null || die "docker is not installed. See $VM_DIR/README.md."
docker compose version >/dev/null 2>&1 || die "the docker compose plugin is missing."

# --- .env, once -------------------------------------------------------------
#
# Generated here and never regenerated. Two of these keys cannot be rotated
# without breaking what already exists: the document grant key invalidates
# every grant already minted, so no bidder could open the booklet they paid
# for, and the bidder master key makes every signing secret a browser holds
# wrong, so the next bid comes back BadSignature. The Postgres password is
# baked into the connection strings of five services.
if [ -f "$ENV_FILE" ]; then
  say "Keeping the existing $ENV_FILE"
else
  say "Generating $ENV_FILE"
  umask 077
  hex() { openssl rand -hex "$1"; }
  pw()  { openssl rand -base64 24 | tr -d '\n/+=' | head -c 24; }
  cat > "$ENV_FILE" <<ENV
# Generated by deploy/vm/deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Not in git.
#
# Do not regenerate these. See the comment in deploy.sh: rotating the grant key
# or the bidder master key breaks grants and signatures that already exist.
POSTGRES_PASSWORD=$(pw)
MINIO_ROOT_USER=eauction
MINIO_ROOT_PASSWORD=$(pw)
KEYCLOAK_ADMIN_USER=admin
KEYCLOAK_ADMIN_PASSWORD=$(pw)
BIDDER_MASTER_KEY=$(hex 32)
DOCUMENT_GRANT_KEY=$(hex 32)
BID_RECEIPT_KEY=$(hex 32)
ENV
  chmod 600 "$ENV_FILE"
  echo "  done — read the Keycloak password with: grep KEYCLOAK_ADMIN_PASSWORD $ENV_FILE"
fi

dc() { docker compose --env-file "$ENV_FILE" -f "$BASE" -f "$OVERRIDE" "$@"; }

# --- check before building --------------------------------------------------
say "Checking the merged configuration"
dc config >/dev/null || die "the compose configuration is not valid; nothing was started."
echo "  ok"

# --- build ------------------------------------------------------------------
#
# Fourteen images on four vCPUs. Expect twenty minutes the first time and a
# couple of minutes after that, since only the layers whose inputs changed are
# rebuilt. The portals are the slow ones: each runs its own npm ci.
say "Building images (this is the long part)"
dc build ${REBUILD} --progress plain 2>&1 | grep -E "^#[0-9]+ (DONE|ERROR)|naming to|ERROR" | tail -40 || true

# --- up ---------------------------------------------------------------------
say "Starting"
dc up -d --remove-orphans

# --- wait -------------------------------------------------------------------
#
# The provisioning jobs are ordered before the services by depends_on, so by
# the time the edge answers, topics exist and the migrations have run.
say "Waiting for the edge"
for i in $(seq 1 60); do
  if curl -fsS --max-time 3 "http://localhost/edge/health" >/dev/null 2>&1; then
    echo "  edge is up"; break
  fi
  [ "$i" = 60 ] && { dc ps; die "the edge did not answer in five minutes."; }
  sleep 5
done

say "Waiting for Keycloak's realm"
for i in $(seq 1 60); do
  if curl -fsS --max-time 3 "http://localhost/auth/realms/eauction" >/dev/null 2>&1; then
    echo "  realm is up"; break
  fi
  [ "$i" = 60 ] && { dc logs --tail=30 keycloak; die "the realm did not import in five minutes."; }
  sleep 5
done

# --- seed -------------------------------------------------------------------
if [ "$SEED" = 1 ]; then
  say "Seeding a plan's worth of history"
  # Publishes events rather than calling the API: auction-admin refuses a start
  # date in the past, and seeded history is in the past by definition.
  docker build -q -f deploy/compose/Dockerfile.seed -t eauction/seed:local . >/dev/null
  NET="$(dc ps --format json bid-catcher 2>/dev/null | head -1 | python3 -c 'import sys,json;d=sys.stdin.read().strip();print(json.loads(d)["Networks"] if d else "")' 2>/dev/null || true)"
  NET="${NET:-compose_default}"
  docker run --rm --network "$NET" eauction/seed:local \
    dotnet eauction-seed.dll --kafka kafka:9092 || echo "  seeding failed; the stack is still up"
fi

# --- what is where ----------------------------------------------------------
say "Up"
dc ps --format "table {{.Name}}\t{{.Status}}" 2>/dev/null || dc ps

cat <<DONE

  bidder portal   http://${HOST}/
  admin portal    http://${HOST}:8081/
  sandbox         http://${HOST}/sandbox/      <- open this one first
  keycloak        http://${HOST}/auth/
  edge health     http://${HOST}/edge/health

  Only 80 and 8081 need to be open in the network security group. Scope them to
  your own address range: this stack runs a payment simulator that settles
  every charge without taking a riyal.

  Accounts are in the realm. The Keycloak admin password is in $ENV_FILE.
DONE
