// <auto-generated />
using System;
using EAuction.Reporting.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EAuction.Reporting.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    [Migration("20261007170521_RenamePlotNumberAddStreetAndFrontage")]
    partial class RenamePlotNumberAddStreetAndFrontage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EAuction.Reporting.Domain.AuctionRecord", b =>
                {
                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BidCount")
                        .HasColumnType("integer");

                    b.Property<string>("BidderVisibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("BookletPriceMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<decimal>("BrokerageFeePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("CascadeStep")
                        .HasColumnType("integer");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ComplianceDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DepositMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("EffectiveEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExtensionsUsed")
                        .HasColumnType("integer");

                    b.Property<long?>("FinalPriceMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<long>("MinIncrementMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OpeningPriceMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phase")
                        .HasColumnType("text");

                    b.Property<int>("PlotCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ScheduledEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ScheduledStartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalAreaSqm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("UnsoldAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WinnerBidderId")
                        .HasColumnType("uuid");

                    b.HasKey("AuctionId");

                    b.HasIndex("ClosedAt");

                    b.HasIndex("Outcome");

                    b.HasIndex("Phase");

                    b.HasIndex("SettledAt");

                    b.ToTable("auction", (string)null);
                });

            modelBuilder.Entity("EAuction.Reporting.Domain.BidderRecord", b =>
                {
                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BidderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("BookletPaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DepositForfeited")
                        .HasColumnType("boolean");

                    b.Property<long>("DepositHeldMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DepositPaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayNameAr")
                        .HasColumnType("text");

                    b.Property<string>("DisqualificationReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DisqualifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EligibilityEndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EligibleAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PaymentRefusedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentRefusedReason")
                        .HasColumnType("text");

                    b.Property<bool>("Won")
                        .HasColumnType("boolean");

                    b.HasKey("AuctionId", "BidderId");

                    b.HasIndex("BidderId");

                    b.HasIndex("EligibleAt");

                    b.ToTable("auction_bidder", (string)null);
                });

            modelBuilder.Entity("EAuction.Reporting.Domain.PlotRecord", b =>
                {
                    b.Property<Guid>("PlotId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AreaSqm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text");

                    b.Property<decimal?>("FrontageMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("Latitude")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Longitude")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlotNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("StreetWidthMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("PlotId");

                    b.HasIndex("AuctionId");

                    b.HasIndex("PlotNumber");

                    b.ToTable("plot", (string)null);
                });

            modelBuilder.Entity("EAuction.Reporting.Domain.SettlementRecord", b =>
                {
                    b.Property<long>("Offset")
                        .HasColumnType("bigint");

                    b.Property<long>("AmountMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BidderId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Offset");

                    b.HasIndex("At");

                    b.HasIndex("AuctionId", "BidderId");

                    b.HasIndex("Purpose", "Outcome", "At");

                    b.ToTable("settlement", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
