// <auto-generated />
using System;
using EAuction.AuctionAdmin.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EAuction.AuctionAdmin.Persistence.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20261004163242_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EAuction.AuctionAdmin.Domain.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("BlindDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<bool?>("BlindRoundEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("BookletDocumentId")
                        .HasColumnType("uuid");

                    b.Property<long>("BookletPriceMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<decimal>("BrokerageFeePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CoverImageDocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<long>("DepositMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxBlindRounds")
                        .HasColumnType("integer");

                    b.Property<int>("MaxExtensions")
                        .HasColumnType("integer");

                    b.Property<long>("MinIncrementMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("OpeningPriceMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<long?>("PendingCandidateAmountMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("PendingCandidateBidderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phase")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("QuietPeriodSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("ReservePriceMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Phase");

                    b.HasIndex("Status");

                    b.ToTable("auction", (string)null);
                });

            modelBuilder.Entity("EAuction.AuctionAdmin.Domain.Award", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("AmountMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BidderId")
                        .HasColumnType("uuid");

                    b.Property<int>("CascadeStep")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ComplianceDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConfirmedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DepositForfeited")
                        .HasColumnType("boolean");

                    b.Property<string>("DisqualificationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("DisqualifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LetterDocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SignedLetterDocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("WinnerNotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId", "CascadeStep")
                        .IsUnique();

                    b.ToTable("award", (string)null);
                });

            modelBuilder.Entity("EAuction.AuctionAdmin.Domain.Plot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AreaSqm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeedNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Latitude")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Longitude")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId", "DeedNumber")
                        .IsUnique();

                    b.ToTable("plot", (string)null);
                });

            modelBuilder.Entity("EAuction.AuctionAdmin.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aggregateid");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aggregatetype");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("RelayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("relayed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("RelayedAt", "CreatedAt");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("EAuction.AuctionAdmin.Domain.Award", b =>
                {
                    b.HasOne("EAuction.AuctionAdmin.Domain.Auction", null)
                        .WithMany("Awards")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EAuction.AuctionAdmin.Domain.Plot", b =>
                {
                    b.HasOne("EAuction.AuctionAdmin.Domain.Auction", null)
                        .WithMany("Plots")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EAuction.AuctionAdmin.Domain.Auction", b =>
                {
                    b.Navigation("Awards");

                    b.Navigation("Plots");
                });
#pragma warning restore 612, 618
        }
    }
}
