// <auto-generated />
using System;
using EAuction.AuctionAdmin.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EAuction.AuctionAdmin.Persistence.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20261008053236_AddPlotLandUse")]
    partial class AddPlotLandUse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EAuction.AuctionAdmin.Domain.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("BidderVisibility")
                        .HasColumnType("integer");

                    b.Property<int?>("BlindDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<bool?>("BlindRoundEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("BookletDocumentId")
                        .HasColumnType("uuid");

                    b.Property<long>("BookletPriceMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<decimal>("BrokerageFeePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<int>("ClerkKeyEpoch")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClerkUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoverImageDocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<long>("DepositMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxBlindRounds")
                        .HasColumnType("integer");

                    b.Property<int>("MaxExtensions")
                        .HasColumnType("integer");

                    b.Property<long>("MinIncrementMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("OpeningPriceMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<long?>("PendingCandidateAmountMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("PendingCandidateBidderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phase")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("QuietPeriodSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("ReservePriceMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<string>("ResultRejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Phase");

                    b.HasIndex("Status");

                    b.ToTable("auction", (string)null);
                });

            modelBuilder.Entity("EAuction.AuctionAdmin.Domain.Award", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("AmountMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BidderId")
                        .HasColumnType("uuid");

                    b.Property<int>("CascadeStep")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ComplianceDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConfirmedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DepositForfeited")
                        .HasColumnType("boolean");

                    b.Property<string>("DisqualificationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("DisqualifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LetterDocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SignedLetterDocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("TransferCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TransferDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransferReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TransferStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("TransferUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("WinnerNotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId", "CascadeStep")
                        .IsUnique();

                    b.ToTable("award", (string)null);
                });

            modelBuilder.Entity("EAuction.AuctionAdmin.Domain.Plot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AreaSqm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("FrontageMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("LandUse")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Latitude")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Longitude")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlotNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("StreetWidthMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId", "PlotNumber")
                        .IsUnique();

                    b.ToTable("plot", (string)null);
                });

            modelBuilder.Entity("EAuction.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aggregateid");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aggregatetype");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("RelayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("relayed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("RelayedAt", "CreatedAt");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("EAuction.AuctionAdmin.Domain.Auction", b =>
                {
                    b.OwnsMany("EAuction.AuctionAdmin.Domain.PublicAttachment", "Attachments", b1 =>
                        {
                            b1.Property<Guid>("AuctionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<Guid>("DocumentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("TitleAr")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("AuctionId", "Id");

                            b1.ToTable("auction");

                            b1.ToJson("attachments");

                            b1.WithOwner()
                                .HasForeignKey("AuctionId");
                        });

                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("EAuction.AuctionAdmin.Domain.Award", b =>
                {
                    b.HasOne("EAuction.AuctionAdmin.Domain.Auction", null)
                        .WithMany("Awards")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("EAuction.AuctionAdmin.Domain.AwardReceipt", "Receipts", b1 =>
                        {
                            b1.Property<Guid>("AwardId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<long>("AmountMinorUnits")
                                .HasColumnType("bigint");

                            b1.Property<Guid?>("DocumentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset>("PaidOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("ReceiptId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("RecordedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("RecordedByUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Reference")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AwardId", "Id");

                            b1.ToTable("award");

                            b1.ToJson("receipts");

                            b1.WithOwner()
                                .HasForeignKey("AwardId");
                        });

                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("EAuction.AuctionAdmin.Domain.Plot", b =>
                {
                    b.HasOne("EAuction.AuctionAdmin.Domain.Auction", null)
                        .WithMany("Plots")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EAuction.AuctionAdmin.Domain.Auction", b =>
                {
                    b.Navigation("Awards");

                    b.Navigation("Plots");
                });
#pragma warning restore 612, 618
        }
    }
}
