// <auto-generated />
using System;
using EAuction.Audit.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EAuction.Audit.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    partial class AuditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EAuction.Audit.Domain.AuditEntry", b =>
                {
                    b.Property<long>("Offset")
                        .HasColumnType("bigint");

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("ActorRoles")
                        .HasColumnType("text");

                    b.Property<Guid?>("ActorSubject")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Malformed")
                        .HasColumnType("boolean");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PreviousHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.HasKey("Offset");

                    b.HasIndex("Action");

                    b.HasIndex("At");

                    b.HasIndex("ActorSubject", "At");

                    b.HasIndex("Subject", "At");

                    b.ToTable("audit_entry", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
